"""Contains constants used throughout the code."""
from pathlib import Path

APP_NAME = "Rozvrhář"
SCHEDULE_FOLDER_PATH = Path(__file__).parent.parent / "schedules"

MAIN_WINDOW_INITIAL_SIZE = (800, 600)
LESSON_WINDOW_INITIAL_SIZE = (600, 400)
SETTINGS_PATH = Path(__file__).parent / "settings.json"

BG_LINE_WIDTH_FACTOR = 1.0 / 500
BG_TEXT_SIZE_FACTOR = 1.0 / 80
BG_TEXT_PADDING_FACTOR = 1.0 / 150
BG_SCHEDULE_PADDING_FACTOR = 1.0 / 50
BG_SIDE_OFFSET_FACTOR = 1.0 / 50
BG_TOP_SIDE_OFFSET_FACTOR = 1.0 / 50
BG_LEFT_SIDE_OFFSET_FACTOR = 1.0 / 7

COLOR_DARKENING_FACTOR = 0.6
LSSN_OUTLINE_WIDTH_FACTOR = 1.0 / 250
LSSN_TEXT_OUTLINE_WIDTH_FACTOR = 1.0 / 7
LSSN_NAME_TEXT_RATIO = 1.0 / 3
LSSN_INFO_TEXT_RATIO = 1.0 / 2
LSSN_TEXT_PADDING_FACTOR =  1.0 / 200
LSSN_UPPER_PART_RATIO = 2/3
